# Generated by Django 4.2.3 on 2023-10-13 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tax_services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('time_zone', models.CharField(default='CST', max_length=255)),
                ('status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='BOOKED', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_holder_name', models.CharField(blank=True, max_length=555, null=True)),
                ('ownership', models.CharField(choices=[('TAXPAYER/SPOUSE', 'TAXPAYER/SPOUSE'), ('JOINT', 'JOINT')], max_length=255)),
                ('routing_number', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('relationship', models.CharField(max_length=255)),
                ('country_of_stay', models.CharField(max_length=255)),
                ('stay_period', models.IntegerField(default=0)),
                ('visa_type', models.CharField(choices=[('H4', 'H4'), ('US Citizen', 'US Citizen'), ('L2', 'L2'), ('Green Card', 'Green Card'), ('Other', 'Other')], max_length=255)),
                ('ssn', models.CharField(blank=True, max_length=255, null=True)),
                ('itin', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_taxes_last_year', models.BooleanField(default=False)),
                ('interest_income', models.BooleanField(default=False)),
                ('dividend_income', models.BooleanField(default=False)),
                ('sold_stocks', models.BooleanField(default=False)),
                ('sold_cryptocurrency', models.BooleanField(default=False)),
                ('foreign_country_income', models.BooleanField(default=False)),
                ('other_benefits', models.BooleanField(default=False)),
                ('last_year_state_tax_refunds', models.BooleanField(default=False)),
                ('foreign_banks_account_balance_exceeding_10000', models.BooleanField(default=False)),
                ('foreign_assets_value_exceeding_50000', models.BooleanField(default=False)),
                ('rental_income_in_usa', models.BooleanField(default=False)),
                ('last_year_1099_misc_nec_income', models.BooleanField(default=False)),
                ('income_description', models.TextField(blank=True, null=True)),
                ('income_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('mode_of_payment', models.CharField(choices=[('INTERNET BANKING', 'INTERNET BANKING'), ('CREDIT/DEBIT CARD', 'CREDIT/DEBIT CARD'), ('PAYPAL', 'PAYPAL')], max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=555, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'INITIATED'), ('PROCESSED', 'PROCESSED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='INITIATED', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(blank=True, choices=[('DIRECT DEPOSIT INTO MY BANK ACCOUNT', 'DIRECT DEPOSIT INTO MY BANK ACCOUNT'), ('PAPER CHECK', 'PAPER CHECK')], max_length=255, null=True)),
                ('tax_docs', models.FileField(blank=True, null=True, upload_to=tax_services.models.get_file_path)),
                ('status', models.CharField(choices=[('INITIATED', 'INITIATED'), ('IN_PROGRESS', 'IN-PROGRESS'), ('COMPLETED', 'COMPLETED')], default='INITIATED', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointments', models.ManyToManyField(to='tax_services.appointment')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_services.bank')),
                ('dependants', models.ManyToManyField(to='tax_services.dependant')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_services.income')),
                ('payments', models.ManyToManyField(to='tax_services.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_services.financialyear')),
            ],
        ),
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_services.taxfiling'),
        ),
        migrations.AddField(
            model_name='income',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filer_income_details', to='tax_services.taxfiling'),
        ),
        migrations.AddField(
            model_name='dependant',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filer_dependants', to='tax_services.taxfiling'),
        ),
        migrations.AddField(
            model_name='bank',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filer_tax_refund_account', to='tax_services.taxfiling'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_services.taxfiling'),
        ),
    ]
