# Generated by Django 4.2.3 on 2023-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_services', '0002_alter_taxfiling_options_alter_financialyear_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxfiling',
            name='service_type',
            field=models.CharField(choices=[('REGULAR', 'REGULAR')], default='REGULAR', max_length=255),
        ),
    ]
