# Generated by Django 4.2.3 on 2023-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_services', '0003_taxfiling_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependant',
            name='itin',
        ),
        migrations.AddField(
            model_name='dependant',
            name='apply_for_itin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dependant',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dependant',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('Other', 'Other')], default='MALE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependant',
            name='job_title',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVINGS', 'SAVINGS'), ('CHECKING', 'CHECKING')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='country_of_stay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
