# Generated by Django 4.2.3 on 2023-10-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_services', '0004_remove_dependant_itin_dependant_apply_for_itin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
