# Generated by Django 4.2.3 on 2023-11-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_services', '0006_taxreturns_taxfiling_tax_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreturns',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
