# Generated by Django 4.2.3 on 2023-11-19 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_services', '0007_taxreturns_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, choices=[('REGULAR', 'REGULAR')], max_length=255, null=True)),
                ('refund_type', models.CharField(blank=True, choices=[('FEDERAL REFUND', 'FEDERAL REFUND'), ('FEDERAL AMENDMENT', 'FEDERAL AMENDMENT'), ('STATE AMENDMENT', 'STATE AMENDMENT'), ('FBAR TAX PAYER', 'FBAR TAX PAYER'), ('FBAR SPOUSE', 'FBAR SPOUSE'), ('FBAR COMBINED', 'FBAR COMBINED'), ('CITY FILING 1', 'CITY FILING 1'), ('CITY FILING 2', 'CITY FILING 2'), ('CITY FILING 3', 'CITY FILING 3'), ('CITY FILING 4', 'CITY FILING 4'), ('EXTENSION FILING', 'EXTENSION FILING'), ('OTHER', 'OTHER'), ('ADVANCE PAYMENT', 'ADVANCE PAYMENT'), ('REFERRAL DISCOUNT', 'REFERRAL DISCOUNT')], max_length=255, null=True)),
                ('standard_refund', models.FloatField(blank=True, default=0, null=True)),
                ('standard_fee', models.FloatField(blank=True, default=0, null=True)),
                ('itemized_refund', models.FloatField(blank=True, default=0, null=True)),
                ('itemized_fee', models.FloatField(blank=True, default=0, null=True)),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('paid_advance', models.FloatField(blank=True, default=0, null=True)),
                ('max_itemized_refund', models.FloatField(blank=True, default=0, null=True)),
                ('max_itemized_fee', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_services.taxfiling')),
            ],
            options={
                'verbose_name': 'Refund',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_by', to=settings.AUTH_USER_MODEL)),
                ('filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_services.taxfiling')),
            ],
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='refunds',
            field=models.ManyToManyField(to='tax_services.refund'),
        ),
    ]
