# Generated by Django 4.2.3 on 2023-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_services', '0008_refund_message_taxfiling_refunds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='ownership',
            field=models.CharField(choices=[('TAXPAYER', 'TAXPAYER'), ('SPOUSE', 'SPOUSE'), ('JOINT', 'JOINT')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='visa_type',
            field=models.CharField(blank=True, choices=[('H4', 'H4'), ('US Citizen', 'US Citizen'), ('L2', 'L2'), ('Green Card', 'Green Card'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
