# Generated by Django 4.2.3 on 2023-11-27 13:18

from django.db import migrations, models
import django.db.models.deletion
import tax_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_services', '0009_alter_bank_ownership_alter_dependant_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_amount',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_description',
        ),
        migrations.RemoveField(
            model_name='taxfiling',
            name='tax_docs',
        ),
        migrations.CreateModel(
            name='TaxDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(blank=True, null=True, upload_to=tax_services.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_services.taxfiling')),
            ],
            options={
                'verbose_name': 'Tax Docs',
            },
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_description', models.TextField(blank=True, null=True)),
                ('income_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filer_other_income_details', to='tax_services.taxfiling')),
            ],
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='other_incomes',
            field=models.ManyToManyField(to='tax_services.otherincome'),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='tax_docs',
            field=models.ManyToManyField(to='tax_services.taxdocs'),
        ),
    ]
