# Generated by Django 4.2.3 on 2023-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tax_filings_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='residental_status',
            new_name='residential_status',
        ),
        migrations.AddField(
            model_name='user',
            name='apply_for_itin',
            field=models.BooleanField(default=False),
        ),
    ]
