# Generated by Django 4.2.3 on 2023-10-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_at_alter_user_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='residential_status',
            field=models.CharField(blank=True, choices=[('H4', 'H4'), ('US Citizen', 'US Citizen'), ('L2', 'L2'), ('Green Card', 'Green Card'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
