# Generated by Django 4.2.3 on 2023-11-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_residential_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='residential_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
